device:
  layer: rpi4

image:
  layer: image-rpios
  boot_part_size: 200%
  root_part_size: 300%
  name: netprobe

layer:
  base: bookworm-minbase
  netprobe: netprobe

# Optional: customize netprobe variables
vars:
  netprobe_install_path: /opt/netmeldr/netprobe 
  netprobe_enable_service: y